### ISSUE TITLE
Audio pitch shift

### ISSUE THREAD

**Issue by RedBrumbler** [roydejong/BeatSaberMultiplayerChat#10]
When the recording frequency in the MicrophoneManager does not match the encoding frequency in the VoiceManager, the audio is pitch shifted upwards.

I imagine the fix for this is to make the encoder actually match the recording frequency of the MicrophoneManager, updating the frequency whenever the mic device is changed

**Comment by roydejong** [comment]
Commit https://github.com/roydejong/BeatSaberMultiplayerChat/commit/a440f110c29dc02a285d64e10cc705b3b05c5ac8 now also adds automatic resampling to 48 kHz. 

I've also changed the default mic target to 48000, it should have been set to that already.
