### ISSUE TITLE
Route slash commands to server instead of broadcasting

### ISSUE THREAD

**Issue by rcelyte** [roydejong/BeatSaberMultiplayerChat#11]
Using ID `0` instead of `127` for messages beginning with "/" would clear up needless noise in the text chat (the server may also whisper command results back in many cases), as well as allowing for commands the host may not want announced to other players (i.e. including private info like room codes).

**Comment by rcelyte** [comment]
This should be fairly simple to implement with `_sessionManager.SendToPlayer(/* ... */, _sessionManager.connectionOwner);`

**Comment by roydejong** [comment]
Makes sense! Done 👍
